// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSC3cE5w2BAdxUTRwDJFhXgXmYmnKrfU',
    appId: '1:426225023888:web:c216ecb316dadb19011115',
    messagingSenderId: '426225023888',
    projectId: 'flutter-authentication-2a819',
    authDomain: 'flutter-authentication-2a819.firebaseapp.com',
    storageBucket: 'flutter-authentication-2a819.appspot.com',
    measurementId: 'G-VS96B2JCV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtNTR8g8rL-4r4H0n133e4hT5i600gx_4',
    appId: '1:426225023888:android:b155f7e037f1ba25011115',
    messagingSenderId: '426225023888',
    projectId: 'flutter-authentication-2a819',
    storageBucket: 'flutter-authentication-2a819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkLdK7MJ_APzoSTD4TeFWEK0loy5a0X8',
    appId: '1:426225023888:ios:e7ee508297880cea011115',
    messagingSenderId: '426225023888',
    projectId: 'flutter-authentication-2a819',
    storageBucket: 'flutter-authentication-2a819.appspot.com',
    iosClientId: '426225023888-1p3ujgtrqkan89sc7api17qglcfv4r4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkLdK7MJ_APzoSTD4TeFWEK0loy5a0X8',
    appId: '1:426225023888:ios:e7ee508297880cea011115',
    messagingSenderId: '426225023888',
    projectId: 'flutter-authentication-2a819',
    storageBucket: 'flutter-authentication-2a819.appspot.com',
    iosClientId: '426225023888-1p3ujgtrqkan89sc7api17qglcfv4r4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );
}
